import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React, {useState, useEffect } from 'react';
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [conversation, setConversation] = useState<Array<string>>([]);
  const [chatboxDisabled, setChatboxDisabled] = useState<boolean>(false);
  const [response, setResponse] = useState<string>('');
  const [query, setQuery] = useState<string>('');

  useEffect(() => {
    if(response) {
      setConversation([...conversation, response])
      setChatboxDisabled(false)
      setResponse('')
      console.log({conversation});
    }
  }, [response])

  useEffect(() => {
    if(query) {
      getResponse().then(json => {
        console.log(json)
        setResponse(json.response);
        setQuery('')
      })
    }
  }, [query])

  const appendToConversation = async (query: string) => {
    setConversation([...conversation, query]);
    setQuery(query);
  }

  const getResponse = async () => {
    const response = await fetch('/api/get-response', {
      method: 'POST',
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({conversation})
    })
    return (await response.json())
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {conversation.map((item,i) => 
            <div className={[i % 2 == 0 ? styles.human: styles.robot, styles.chatcontainer].join(" ")} key={i}>
              {i%2==0? <>
                {/* <Image src="public/human.png" alt="human" width={100} height={100}/>  */}
                <p className={styles.chatlabel}>human</p>
              </> : <> 
                {/* <Image  src="public/robot.png" alt="robot" width={100} height={100}/> */}
                <p className={styles.chatlabel}>robot</p>
              </>}
              <p className={styles.chattext}>{item}</p>
            </div>
          )}
        </div>
        <div className={styles.chatbox}>
          <ChatBox addToList={appendToConversation} disabled={chatboxDisabled} setDisabled={setChatboxDisabled} />
        </div>
      </main>
    </>
  )
}

const ChatBox = ({ addToList, disabled, setDisabled }: {addToList: any, disabled: boolean, setDisabled: any}) => {
  const [message, setMessage] = useState('');

  const handleKeyDown = (e: any) => {
    const keyCode = e.keyCode;
    if(keyCode === 13 && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e);
    }
  }
  const handleChange = (e: any) => {
    setMessage(e.target.value);
  };

  const handleSubmit = (e: any) => {
    e.preventDefault();
    addToList(message);
    setMessage('');
    setDisabled(true);
  };

  return (
    <form onSubmit={handleSubmit} className={styles.description}>
      <fieldset>
        <textarea value={message} onChange={handleChange} onKeyDown={handleKeyDown}/>
        <button type="submit" disabled={disabled}>Send</button>
      </fieldset>
    </form>
  );
};